name: Variables define in workflow level 

on: 
 workflow_dispatch
   
env: 
 platform: github Actions :)  # entire workflow level, we can access this variables.

jobs: 
 variablesDefine: 
   runs-on: ubuntu-latest
   env: 
     greeting: Hello       # job level

   steps: 
     - name: display variables values 
       run: echo $greeting $message $platform
       env: 
        message: Welcome to        # steps level
     - name: dispaly other vars 
       run : |
           echo "Displaying in different stage"
           echo $greeting $message $platform