name: 04-defining context variables

on: workflow_dispatch 

jobs: 
 contextVars:
    runs-on: ubuntu-latest

    steps: 
      - name: accessing the github context variables 
        run: |
             echo "Repository_Url: ${{github.github.repositoryUrl}}"
             echo "triggered_By: ${{github.triggering_actor}}"
             echo "workspace: ${{github.workspace}}"
             echo "Workflow_Number: ${{github.run_number}}"
             echo "attempt_No": ${{github.run_attempt}} 

