name: 06-secrets

on: workflow_dispatch


env: 
 ACTIONS_STEP_DEBUG: ture


jobs: 
  secretaccess:
    runs-on: ubuntu-latest 

    steps: 
      - name: access secret var which is defined in reporitory 
        run: |
         echo "secret is:${{secrets.SECRET_NAME}}"
         ${{secrets.SECRET_NAME}}