name: 06-secrets

on: workflow_dispatch


jobs: 
  secretaccess:
    runs-on: ubuntu-latest 

    steps: 
      - name: access secret var which is defined in reporitory 
        run: echo "secret is:${{secrets.secretName}}"
        ${{secrets.secretName}}