name: Trigger workflow on Cron

on:
 schedule:
   - cron: '* * * * *'
jobs:
 TriggerWorkflow:
    runs-on: ubuntu-latest
    steps:
      - name: display Message 
        run: |
           echo "Workflow triggered by cron schedule"
           
      
