name: Deploy Flask App

on: 
 push:
  branches:
   - main
 workflow_dispatch: 

env:
  Healthcheck_endpoint: http://52.91.53.62:5000

jobs:
    Build:
        runs-on: self-hosted
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            
            - name: setUp Python environment
              uses: actions/setup-python@v4
              with:
                python-version: 3.9

            - name: Setup Virtual Environment
              run: |
                sudo apt install python3.12-venv -y
                python3 -m venv venv
                source venv/bin/activate
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip3 install -r requirements.txt
            
            - name: Run unit Tests
              run: |
               python3 -m unittest test_app.py

            - name: Deploy App
              run: |
                 source venv/bin/activate
                 nohup python3 app.py > app.log 2>&1 &
                 sleep 5  # Give some time for the app to start
                 netstat -ant
    HealthCheck:
        runs-on: self-hosted
        needs: Build
        steps:
          - name: Perform Health Check
            run: |
               for i in {1..10}; do 
                   curl -s -o /dev/null -w "%{http_code}" $Healthcheck_endpoint | grep "200" && echo "Health check Passed ..." && exit 0 || echo "waiting for service ...";
                   sleep 5
               done;
               echo "Health check failed ..." && exit 1

